const assert=require('node:assert/strict');
const {DEFAULTS,validateSettings}=require('./settings.js');
assert.equal('openRouterApiKey' in DEFAULTS,true);
assert.equal('apiKey' in DEFAULTS,false);
assert.equal('appSessionToken' in DEFAULTS,true);
assert.equal(validateSettings({serviceUrl:'https://example.test/'}).serviceUrl,'https://example.test');
assert.throws(()=>validateSettings({serviceUrl:'http://external.example'}));
assert.equal(validateSettings({serviceUrl:'http://localhost:8787/'}).serviceUrl,'http://localhost:8787');
assert.equal(validateSettings({openRouterApiKey:'sk-or-v1-'+'a'.repeat(32)}).openRouterApiKey,'sk-or-v1-'+'a'.repeat(32));
assert.throws(()=>validateSettings({openRouterApiKey:'not-a-key'}),/OpenRouter/);
assert.equal(DEFAULTS.ocrEngine,'ppocr-v5-wasm');
assert.equal(DEFAULTS.whisperModel,'small-webgpu');
assert.equal(validateSettings({whisperModel:'base'}).whisperModel,'base-wasm');
assert.equal(validateSettings({whisperModel:'base-wasm'}).whisperModel,'base-wasm');
console.log('settings: secure service configuration passed');
