const assert=require('node:assert/strict'),fs=require('node:fs');
const html=fs.readFileSync('sidepanel.html','utf8'),js=fs.readFileSync('sidepanel.js','utf8');
assert.match(html,/lib\/service-client\.js/);
assert.match(html,/서비스 URL과 앱 세션 토큰/);
assert.doesNotMatch(html,/id="(?:apiKey|provider|syncCb)"/);
assert.doesNotMatch(js,/settings\.apiKey|allowRemoteOcr|callRemote\(/);
assert.match(js,/ServiceClient\.summary/);
assert.doesNotMatch(js,/URL\.createObjectURL|new Blob\(|buildTimeline\s*\(/);
assert.match(html,/id="pdfBtn"/);assert.match(html,/id="notionBtn"/);assert.match(html,/id="popoutBtn"/);
console.log('panel: secure thin service adapter checks passed');
