const test=require("node:test"),assert=require("node:assert/strict");
require("./evidence");require("./visual-gate");const {CaptureSession}=require("./session");const {AudioSegments}=require("./audio-segments");
function session(){global.document={createElement:()=>({currentTime:0,muted:true,srcObject:null})};return new CaptureSession({id:"s",generation:1,stream:{getTracks:()=>[]},options:{},emit:()=>{}});}
test("STOP captures final frame then drains once; disposal clears notes and texts",async()=>{const s=session();s.status="running";let captures=0,cleanups=0;s.captureVisual=async()=>{captures++;};s.cleanup=async()=>{s.closed=true;cleanups++;};const a=s.stop(),b=s.stop();assert.equal(a,b);await a;assert.equal(captures,1);assert.equal(cleanups,1);assert.equal(s.status,"completed");s.summary={title:"synthetic"};s.store.add({text:"private",time:0});await s.dispose();assert.equal(s.summary,null);assert.equal(s.store.items.length,0);});
test("late ASR result cannot mutate disposed session",()=>{const s=session();s.closed=true;s.asrBusy=true;s.onAsr({type:"TRANSCRIBED",text:"late"});assert.equal(s.store.items.length,0);});
test("diagnostic logs publish as soon as they are appended",()=>{let publishes=0;const s=new CaptureSession({id:"log",generation:1,stream:{getTracks:()=>[]},options:{},emit:()=>publishes++});s.log("[음성] 입력 연결됨");assert.equal(publishes,1);assert.match(s.state().debug.join("\n"),/입력 연결됨/);});
test("session state exposes only the latest three recognition lines",()=>{const s=session();for(const [source,text] of [["asr","음성 하나"],["ocr","화면 둘"],["asr","음성 셋"],["ocr","화면 넷"]])s.store.add({source,text,t0:s.store.items.length,t1:s.store.items.length+1});assert.deepEqual(s.state().recent.map(item=>[item.source,item.text]),[["ocr","화면 둘"],["asr","음성 셋"],["ocr","화면 넷"]]);});
test("ASR diagnostics expose throughput without logging transcript text",()=>{const empty=session();empty.status="running";empty.asrBusy=true;empty.activeAudio={time:2,t1:3,audioSeconds:1};empty.asrStartedAt=performance.now()-10;empty.onAsr({type:"TRANSCRIBED",text:""});assert.match(empty.state().debug.join("\n"),/인식 결과 없음/);assert.equal(empty.store.items.length,0);const spoken=session();spoken.status="running";spoken.asrBusy=true;spoken.audioQueue=[{audioSeconds:1.5}];spoken.activeAudio={time:3,t1:4,audioSeconds:1};spoken.asrStartedAt=performance.now()-10;spoken.onAsr({type:"TRANSCRIBED",text:"private lecture words"});const debug=spoken.state().debug.join("\n");assert.match(debug,/인식 완료 · 캡처 1\.0초 · 추론 [\d.]+초 · RTF [\d.]+ · 대기 1건 · 1\.5초/);assert.doesNotMatch(debug,/private lecture words/);assert.equal(spoken.store.items.length,1);const failed=session();failed.status="running";failed.asrBusy=true;failed.audioQueue=[{audioSeconds:2}];failed.activeAudio={time:4,t1:5,audioSeconds:1};failed.asrStartedAt=performance.now()-10;failed.fail=()=>{};failed.onAsr({type:"ERROR",error:"synthetic failure"});assert.match(failed.state().debug.join("\n"),/Whisper 오류 · 캡처 1\.0초 · 추론 [\d.]+초 · RTF [\d.]+ · 대기 1건 · 2\.0초/);});
test("STOP cancels pending model preparation without waiting for its timeout",async()=>{const {timeout}=require('./session');const s=session();const pending=timeout(new Promise(()=>{}),90000,'model timeout',s.startController.signal);const assertion=assert.rejects(pending,/취소/);await s.stop();await assertion;assert.ok(s.closed);});
test("voice segmentation flushes tail and splits before unbounded growth",()=>{const jobs=[];const a=new AudioSegments(j=>jobs.push(j));for(let i=0;i<220;i++)a.push(new Float32Array(1600).fill(.1),i/10,0,1);a.flush();assert.ok(jobs.length>=2);assert.equal(jobs[0].audio.length,320000);assert.ok(jobs[1].audio.length>16000);assert.ok(a.length===0);});
test("voice at the 20-second boundary is emitted",()=>{const jobs=[];const a=new AudioSegments(j=>jobs.push(j));for(let i=0;i<200;i++)a.push(new Float32Array(1600).fill(.01),i/10,0,1);assert.equal(jobs.length,1);assert.equal(jobs[0].audio.length,320000);});
test("audio normalization raises quiet speech without clipping",()=>{const {normalizeAudio}=require("./session");const audio=new Float32Array([.01,-.01]);normalizeAudio(audio);assert.ok(Math.abs(audio[0]-.1)<1e-6);assert.ok(Math.abs(audio[1]+.1)<1e-6);});
test("auto Whisper language is Korean-first instead of the library English default",()=>{const {whisperLanguage}=require("./session");assert.equal(whisperLanguage("auto"),"korean");assert.equal(whisperLanguage("ko"),"korean");assert.equal(whisperLanguage("en"),"english");});
test("audio-only start fails honestly if the tab has no audio",async()=>{global.document={createElement:()=>({currentTime:0,muted:true,srcObject:null,videoWidth:1280,play:async()=>{}})};const s=new CaptureSession({id:"screen",generation:1,stream:{getTracks:()=>[],getAudioTracks:()=>[]},options:{ocrEnabled:false,whisperEnabled:true},emit:()=>{}});await assert.rejects(s.start(),/오디오가 없습니다/);assert.equal(s.status,"failed");assert.ok(s.closed);});
test("rate changes flush the previous audio clock mapping",()=>{const s=session();s.metadata={rate:1,paused:false};let flushes=0;s.segments={flush:()=>flushes++};s.updateMetadata({rate:2,paused:false,epoch:0});assert.equal(flushes,1);});
test("silent pre-roll clock begins at the retained samples",()=>{const a=new AudioSegments(()=>{});for(let i=0;i<10;i++)a.push(new Float32Array(1600),i/10,0,1);assert.ok(Math.abs(a.start-.6)<1e-9);});
